ReDI-School/connect

redi-connect-admin/src/App.js
redi-connect-backend/common/models/red-profile.json
redi-connect-backend/scripts/seed-database.js
redi-connect-front/src/components/ContactInfo.tsx
redi-connect-front/src/pages/app/me/Me.tsx
redi-connect-front/src/pages/app/me/steps/Step4ContactData.tsx
redi-connect-front/src/pages/front/signup/factory.tsx
redi-connect-front/src/pages/front/signup/steps/Step4ContactData.tsx
redi-connect-front/src/types/RedProfile.ts

feat(all): add github profile url to mentor/mentee contact information

---

redi-connect-front/package.json
redi-connect-front/src/components/atoms/Button.scss
redi-connect-front/src/components/atoms/FormInput.tsx
redi-connect-front/src/pages/front/login/Login.scss
redi-connect-front/src/pages/front/login/Login.tsx
redi-connect-front/src/pages/front/reset-password/RequestResetPasswordEmail.tsx
redi-connect-front/src/pages/front/reset-password/SetNewPassword.tsx
redi-connect-front/src/pages/front/signup-existing/ResetPassword.tsx
redi-connect-front/src/services/api/api.tsx
redi-connect-front/src/styles/_forms.scss
redi-connect-front/src/styles/main.scss
redi-connect-front/yarn.lock

Adding the new UI for the password request flow. 
The error handling is not changed, as the design is missing so I left the original app notifications in there. There will be a follow up task there to handle those features when the design is delivered.

feat(front): new ui password reset

---

redi-connect-backend/lib/email/templates/mentoring-session-logged-email.berlin.mjml
redi-connect-backend/lib/email/templates/mentoring-session-logged-email.munich.mjml
redi-connect-backend/lib/email/templates/mentorship-cancelation-email-mentee.berlin.mjml
redi-connect-backend/lib/email/templates/mentorship-request-email.berlin.mjml
redi-connect-backend/lib/email/templates/mentorship-request-email.munich.mjml

Note:
- `4. Verify email for Munich redirects to Berlin` was redirecting properly in production

fix(backend): post launch bug fixes 'emails'

---

redi-connect-front/src/components/molecules/Modal.scss
redi-connect-front/src/components/molecules/Modal.tsx
redi-connect-front/src/components/organisms/ApplyForMentor.tsx
redi-connect-front/src/styles/_variables.scss

Currently there is a bug with the modal which is making it impossible to scroll the modal content it self on small screens where the content is longer than the screen size.
The bug is testable on the find the mentor page when you open a mentor profile and trigger the apply for mentorship overlay. 
I already deployed the fixed version to the Berlin staging. The Munich stayed the same so you can see the bug. 
This is the fix for it, if you are fine with it it would be also good to release this. 
Cheers,
Endre

fix(front): fix modal scrolling

---

redi-connect-front/src/components/atoms/Logo.tsx
redi-connect-front/src/components/organisms/Navbar.scss

Just a quick fix to remove the hover effect (underline) in Safari

fix(front): underline on hover in safari removed

---

redi-connect-front/src/pages/app/profile/Profile.tsx

Since you are both not working on it atm and I'm on my sabbatical for at least a month from tomorrow ongoing I requested both of you ... whoever is first 😄 
In the end it was a small fix that should solve the issue to not just see an empty headline if there is no information given be the mentor / mentee who owns the profile.

fix(front): if info is not given it won't be visible in the profile

---

redi-connect-infrastructure/README.md
redi-connect-infrastructure/_main.tf

Fixes https://github.com/talent-connect/connect/issues/234
Now you can visit http://cdn-endpoint-front-staging-redi.azureedge.net/front/home which will redirect you to `https`

fix: redirects http to https on static website

---

redi-connect-backend/server/server.js

This is a partial revert of #225 that removed the backend's ability to run the backend in https mode using node's `https`, with an SSL cert + private key file hosted on the server-side.
@paschalidi, this is needed for the short while that the backend needs to operate under both Azure and AWS. I see things are more elegant on Azure with SSL provided via some middleware, but nothing similar is set up for the current production backend on AWS. On booting the backend, I'll simply use a USE_HTTPS=1 flag.
Please make sure to check in with me on backend stuff like this. I updated the prod backend to the latest commit, and did a lot of head scratching and taking down the backend, while figuring out what was wrong with my SSL certs, then saw they weren't used at all 😅
Merging immediately as this …

Backend feature flag to use `https` instead of default `http`

---

apps/redi-talent-pool/src/components/molecules/CvPdfPreview.tsx

This PR fixes an issue caught by Miriam, where we don't show the month if the user selects January in the experience dates.
**Before:**
**After:**

Hotfix not showing January in Experience section

---

apps/api/common/models/tp-job-listing.js

Fixes #407 
We can also add the createdAt records for previously created job listings, using the trick below:
```
db.TpJobListing.update(
{ _id:ObjectId("__id__")}, 
{ $set: { createdAt: ObjectId('__id__').getTimestamp() } }
)
```

Add createdAt record for tp job listings

---

apps/api/lib/email/email.js

None
I realized this was a quick-win feature, so I went ahead and coded it. 
Emails sent will now be prefixed with `[DEMO ENVIRONMENT]` if sent from the demo env, or with `[DEV ENVIRONMENT]` if working locally. Production emails stay as they are.
This should decrease confusion about where emails are coming from. Especially for Miriam, Johanna & co, now that all emails are bcc-ed to career@redi-school.org.

feat(api): prefix demo/dev env email subject lines

---

apps/admin-panel/src/App.jsx
apps/api/common/models/tp-company-profile.js
libs/shared-types/src/lib/TpCompanyProfileState.ts

Fixes #459 
This PR enables Talent Pool Company Profiles to be approved even before they fill the required fields and submit for approval, through Admin Panel. This will allow us to have no issues when two or more recruiters want to use Talent Pool by creating different accounts for the same company.

[Issue #459] Enable approving companies without submit

---

apps/redi-connect/src/components/molecules/ReadOccupation.tsx
apps/redi-connect/src/components/molecules/ReadRediClass.tsx
apps/redi-connect/src/components/organisms/ApplicationCard.tsx
apps/redi-connect/src/components/organisms/ConfirmMentorship.tsx
apps/redi-connect/src/components/organisms/SideMenu.tsx
apps/redi-connect/src/pages/app/applications/Applications.tsx
apps/redi-connect/src/redux/matches/selectors.ts
libs/shared-types/src/lib/RedMatch.ts

#344 and #366
In this PR, I also fixed the following:
* placeholder text in the ConfirmMentorship component to be the name of a mentee instead of the name of a mentor
* display ReDI class in the mentee profile
Non-activated mentee:
Non-activated mentor:
Activated mentee with no applications:
Activated mentor with no applications:
A user (mentor) with different applications:

Feat(con): always show applications page for mentors & mentees

---

apps/redi-talent-pool/src/pages/app/me/MeJobseeker.tsx
libs/shared-types/src/lib/TpJobseekerProfile.ts

#480 
This PR adds a simple checkbox to toggle `isJobFair2022Participant` field for TpJobseekers. This field will help us filter jobseekers by their participation status to JF2022.

Add Job Fair 2022 Toggle for MeJobseeker page

---

apps/redi-talent-pool/src/components/organisms/company-profile-editables/EditableJobPostings.tsx
libs/shared-types/src/lib/TpJobListing.ts

#480
This PR adds a simple checkbox to toggle the `isJobFair2022JobListing` field for `TpJobListing` in the page `http://localhost:2999/app/me`. This field will help us filter job listings by their participation status to JF2022.

Add Job Fair 2022 Toggle for new/edit job posting modal

---

apps/redi-talent-pool/src/pages/app/browse/BrowseCompany.tsx
apps/redi-talent-pool/src/services/api/api.tsx

Ref #480 
This PR adds a checkbox as a new filter toggle for job seekers, filtering them by `isJobFair2022Participant`

[#480] Add Job Fair 2022 filter for Jobseekers

---

apps/redi-talent-pool/src/pages/app/browse/BrowseJobseeker.tsx
apps/redi-talent-pool/src/pages/app/me/MeJobseeker.tsx
apps/redi-talent-pool/src/services/api/api.tsx

#480 
This PR adds a checkbox as a new filter toggle for job listings, filtering them by `isJobFair2022JobListing`

[#480] Add Job Fair 2022 filter for Job Listings

---

apps/admin-panel/src/App.jsx

Ref #480
Toggle in admin-panel for Job Seekers and Job Listings (show/edit).
A remark is that the two `BooleanInput` will save `false` in the record.
As far as I understood we want to be consistent and have `undefined`/`true` in the records.
[react-admin](https://marmelab.com/react-admin) latest version `3.19.5` says we could use [parse](https://marmelab.com/react-admin/Inputs.html#recipes) and `format`.
We use `react-admin` version `2.99` but it _should_ anyway be based on [react-final-form](https://final-form.org/docs/react-final-form/types/FieldProps#parse) which should have `parse`/`format`.
It would be nice to use something like this, but maybe I got it wrong and it does not work for another reason:
```
<BooleanInput 
initialValue={false}
parse={(v) => (v === false) ? undefined : v} …
```

[#480] Add Job Fair 2022 toggle in admin-panel

---

apps/admin-panel/src/App.jsx

None. This was a last-minute request to add the gender field to the `RedProfiles` csv export
This is already deployed to https://connect-admin.redi-school.org

feat(admin): customize RedProfiles csv export

---

apps/api/scripts/fix-orphaned-red-users.js

This repairs the maintenance scripts that deletes orphaned RedUsers, i.e. users that have don't have any profiles in either Connect or Talent Pool. This script has been out of commission since we launched TP, as it worked for CON only. It now takes care of deleting users what have no profiles whatsoever, and as such are truly orphaned.

chore(api): fix the 'remove orphaned users' script

---

apps/api/common/models/red-user.js

As per discussion in Slack, there's a way to improve the sign-up to CON "via TP" by setting the CON profile's rediLocation based on the course they've registered in the TP profile.

feat(api): on con-via-tp sign-up, set rediLocation based on course

---

apps/admin-panel/src/App.jsx

Close #514 
Verify that the two new columns `Completed on` and `Number of mentoring sessions` are correctly populated.
---
Show/Edit for `matchCompletedOn` in `RedMatchShow` / `RedMatchEdit`

WIP [CON/Admin Panel] Adding additional columns to Redmatches

---

apps/admin-panel/src/App.jsx
apps/redi-talent-pool/src/components/organisms/company-profile-editables/EditableJobPostings.tsx
apps/redi-talent-pool/src/pages/app/browse/BrowseJobseeker.tsx
apps/redi-talent-pool/src/services/api/api.tsx
libs/shared-types/src/lib/TpJobListing.ts

As per conversations in Slack, we want to drop the `isJobFair2022JobListing` property since it won't be part of the data migration to Salesforce, and it's deprecated anyways.

feat(tp): remove `isJobFair2022JobListing`

---

apps/redi-talent-pool/src/components/organisms/jobseeker-profile-editables/EditableImportantDetails.tsx
apps/redi-talent-pool/src/pages/app/jobseeker-profile/JobseekerProfile.tsx
apps/redi-talent-pool/src/pages/app/me/MeJobseeker.tsx

This PR hides the full address of jobseekers from companies.
**Before:**
**After:**

Hide full address of jobseekers from companies

---

apps/redi-talent-pool/src/components/organisms/company-profile-editables/EditableJobPostings.tsx
apps/redi-talent-pool/src/pages/app/browse/BrowseJobseeker.tsx
apps/redi-talent-pool/src/services/api/api.tsx

This PR adds a new field for job listings, called `federalState`. This is very similar to what we have done in #516, where we have added the same field for jobseekers.
Using this field, companies will be able to select a specific federal state in Germany when they open a job post, and jobseekers will be able to filter the job listings, using a filter box in the Browse page.

Add Federal State field & filtering for Joblistings

---

apps/admin-panel/src/App.jsx
apps/redi-talent-pool/src/components/organisms/company-profile-editables/EditableJobPostings.tsx
libs/shared-types/src/lib/TpJobListing.ts

This field doesn't serve any purpose. I've checked and double-checked the database, no job listing has any non-empty value for the `desiredExperience` field. And it's not a field we give users in the `<EditableJobPostings />`.
Hence, dropping ahead of the Salesforce migration.

refactor(tp): drop non-used field

---

apps/redi-talent-pool/src/pages/app/me/MeJobseeker.tsx

Since the ReDI Job Fair 2022 has passed, no need to have this checkbox in TpJobseeker Profile page anymore

Remove JobFair2022 checkbox from jobseeker profile

---

apps/redi-talent-pool/src/components/organisms/company-profile-editables/EditableJobPostings.tsx
apps/redi-talent-pool/src/pages/app/browse/Browse.scss
apps/redi-talent-pool/src/pages/app/browse/BrowseJobseeker.tsx
apps/redi-talent-pool/src/pages/app/job-listing/JobListing.tsx
apps/redi-talent-pool/src/services/api/api.tsx
libs/shared-types/src/lib/TpJobListing.ts
libs/talent-pool/config/src/lib/talent-pool-config.ts

This PR adds a new field for TpJobListing entity, `isRemotePossible`. Using this field
* companies can mark the job listings they open as Remote Possible 
* This information will be shown in a Job Listing page as in the screenshots below
* Jobseekers can filter job openings using a new filter regarding this information

Add isRemotePossible for TpJobListings

---

apps/admin-panel/src/App.jsx
apps/redi-talent-pool/src/components/organisms/JobseekerProfileCard.scss
apps/redi-talent-pool/src/components/organisms/JobseekerProfileCard.tsx
libs/shared-types/src/lib/TpJobseekerProfile.ts

This PR adds a new field `isHired` for TpJobseeker entity. This field is meant to be used for promoting our hired jobseekers in the Browse section for companies. Until now, the solution for this was updating these people's names with JUST HIRED or HIRED, however this would cause us some headache over the Salesforce migration, hence this result.
This field will be only toggled through the Admin Panel (and Salesforce Panel after the migration). Jobseekers won't be able to mark themselves as Hired. (yet? Maybe we can also discuss this as a feature to implement)
You can see the screenshots of the simple design I came up with. @miriam-aha Please let me know if we should come up with a better design for this.
PS: I added the toggle by replacing `isJobFair2022Participant` with `isHired` in the …

Add isHired field and Tag for TpJobseekers

---

apps/api/common/models/red-user.js

No Issue
This PR attempts to fix a nasty edge-case we have when logging in to Talent Pool. TP Login logic works as following:
```
Login Attempt in Talent Pool
User has Jobseeker Profile? => Continue Login
User has NO Connect Profile? => Continue Login
Otherwise => Create a Jobseeker Profile using the existing Con Profile and login to that 
```
This logic works perfectly to reuse the same Red User and Login Credentials for existing Mentors or Mentees, when they want to login as a Jobseeker. However, it fails for a very edge case, which a Mentor or Mentee wants to login as a Company Representative. The system basically decides to create a Jobseeker profile for everyone in that case.
To prevent this from happening, I'm slightly changing the logic above, into this:
```
Login Attempt in Talent …
```

Avoid creating ToJobseekerProfile for Con Users with Company Profile

---

apps/redi-talent-pool/src/components/organisms/jobseeker-profile-editables/EditableImportantDetails.tsx
apps/redi-talent-pool/src/components/organisms/jobseeker-profile-editables/EditableNamePhotoLocation.tsx
apps/redi-talent-pool/src/services/api/api.tsx
libs/shared-types/src/lib/TpJobseekerCv.ts
libs/shared-types/src/lib/TpJobseekerProfile.ts

#570 
This PR adds a new "important detail" for Jobseekers. They will be able to add if they are willing to relocate. This information will be shown in the Jobseeker Profile page under "Important Details" section and also used when filtering jobseekers with their state.

[Issue 570] Willing To Relocate for TpJobseekers

---

apps/redi-talent-pool/src/components/organisms/Avatar.scss
apps/redi-talent-pool/src/components/organisms/Avatar.tsx
apps/redi-talent-pool/src/components/organisms/company-profile-editables/EditableNamePhotoLocation.tsx
apps/redi-talent-pool/src/pages/app/job-listing/JobListing.tsx
libs/shared-atomic-design-components/src/lib/molecules/Modal.scss
libs/shared-utils/src/lib/crop-image.ts

#534 
This PR adds support for Logo cropping for TP Companies. To support this feature better, I'm introducing also square logos for companies, which can be seen in the screenshots below:

[Issue 534] Add image cropping & square logos for Companies

---

.github/workflows/mirror-to-private-repo.yml

@helloanil, I'm replacing one plugin with another, for the one-way sync mechanism. Turns out the former one was **deleting** branches on the ffg repo that they'd created 😆 Not what we want

Fix broken one-way sync

---

apps/admin-panel/src/App.jsx
apps/redi-connect/src/config/config.tsx
apps/redi-talent-pool/src/pages/app/browse/Browse.scss
apps/redi-talent-pool/src/pages/app/browse/BrowseCompany.tsx
apps/redi-talent-pool/src/pages/app/me/MeJobseeker.tsx
apps/redi-talent-pool/src/services/api/api.tsx
libs/shared-types/src/lib/TpJobseekerProfile.ts

This PR adds a special toggle for the ReDI Job Fair 2023. Three important additions in the codebase for this are:
- Adding a Checkbox in the Jobseeker Account/Profile page, to allow them check the box if they are participating ReDI Job Fair 2023
- Adding a Checkbox in the Browsing Jobseekers page for companies to filter jobseekers that attend the Job Fair.
- Adding a visible information section in the Admin Panel, for ReDI Admins to see if a jobseeker attends the Job Fair.

ReDI Job Fair 2023 Toggle

---

apps/api/lib/email/tp-templates/jobseeker-validate-email-address-successful.mjml
apps/redi-connect/src/components/organisms/ProfileCard.scss
apps/redi-connect/src/components/organisms/ProfileCard.tsx
apps/redi-talent-pool/src/components/organisms/JobListingCard.scss
apps/redi-talent-pool/src/components/organisms/JobListingCard.tsx
apps/redi-talent-pool/src/components/organisms/JobseekerProfileCard.scss
apps/redi-talent-pool/src/components/organisms/JobseekerProfileCard.tsx
apps/redi-talent-pool/src/components/organisms/company-profile-editables/EditableJobPostings.tsx
apps/redi-talent-pool/src/pages/app/browse/BrowseCompany.tsx
apps/redi-talent-pool/src/pages/app/browse/BrowseJobseeker.tsx
apps/redi-talent-pool/src/pages/front/signup/SignUpComplete.tsx

In this PR, the following miscellaneous fixes were made:
1. Added link for the TP website to the jobseeker "validate successful" e-mail.
2. Added an illustration to the TP sign-up complete page (the blue side on the left was empty before).
3. Made a job posting & jobseeker profile card to open in a new tab (ticket [#547](https://github.com/talent-connect/connect/issues/547)).
4. Made a mentor/mentee profile card to open in a new tab (ticket [#656](https://github.com/talent-connect/connect/issues/656).

fix(tp/con): open cards in a new tab

---

apps/redi-talent-pool/src/pages/app/browse/BrowseCompany.tsx
apps/redi-talent-pool/src/pages/app/browse/BrowseJobseeker.tsx
apps/redi-talent-pool/src/pages/app/me/MeCompany.tsx
apps/redi-talent-pool/src/pages/app/me/MeJobseeker.tsx
apps/redi-talent-pool/src/services/api/api.tsx

Ticket #639
PR https://github.com/talent-connect/connect/pull/651
- On the 'Browse job listings' page, added the checkbox filter so the job seekers can filter job listings posted by companies attending the Job Fair.
- Hid this checkbox from the Company profile, Jobseeker profile, and both 'Browse' pages until the next Job Fair date announced
@fortini, since here we are displaying job postings and not profiles of companies attending the Job Fair, we have to come up with a better name for this filter before we make it available to job seekers again.

feat(tp): Add filter job listings posted by companies attending the Job Fair

---

apps/api/scripts/.gitignore
apps/nestjs-api/src/salesforce-api/sf-api.repository.ts

None
All queries returned from SF are currently cached for up to ten minutes before being cleared/invalidated. This PR adjusts this down to five minutes.
Do note that there are other things that clear/invalidate the cache:
- any mutations/writes
- certain events in Salesforce (such as approvals)

feat(nestjs-api): cache data from sf for 5 min instead of 10 min

---

apps/nestjs-api/src/tp-job-listings/tp-job-listings.service.ts

#723 
This PR adds a new filter for findAllVisibleJobListings to check if the related Account (the company) is approved or not.

[#723] Fix showing job listings from non-approved companies

---

apps/api/common/models/red-user.js
libs/data-access/src/lib/graphql-client.ts

#728 
This PR handles the situations where the JWT token expires, graphql returns 401 but Frontend cannot handle it. Now the middleware will alert the user that their session has expired, clear the localstorage and redirect them to the login page.
More information can be seen in the ticket above.

[CON/TP]: Handle the "unauthorized error" case when the JWT token expires

---

apps/redi-talent-pool/src/pages/app/browse/BrowseCompany.tsx
apps/redi-talent-pool/src/pages/app/browse/BrowseJobseeker.tsx

#699 
This PR adds the total number of Job Postings /Jobseekers to the title of the search in the Browse page.
Previous Title in Browse page for Jobseekers:
Current Title in Browse page for Jobseekers:
Previous Title in Browse page for Companies:
Current Title in Browse page for Companies:

[TP/Browse page] Adds the total number of Job Postings /Jobseekers 

---

apps/redi-talent-pool/src/components/organisms/jobseeker-profile-editables/EditableEducation.tsx
apps/redi-talent-pool/src/components/organisms/jobseeker-profile-editables/EditableProfessionalExperience.tsx

Bug report: Some students have reported that it is not possible to add new education or experience records. 
This error may occur when users have many records or try to save/add many.
Screenshot of the error:
Here we use the same approach as when saving language records - we save them one by one.

fix(tp): save education and experience records one by one

---

apps/redi-talent-pool/src/pages/front/login/Login.tsx

:x: When I log in to any of my existing TP users, I get this error (screenshot). No errors in the console, but if I go to the account, I can see my logged-in profile.
This is happening because we try to load the CON profile for every TP user trying to log in, and if a CON profile doesn't exist, the graphql query returns 404, which is caught as an exception in the try catch block, thus stopping the whole process and sets the error messages in the login form.
We need to attempt loading the CON profile only when the TP profile for the RedUser doesn't exist, so we can create a new TP Profile based on that CON profile. If a TP Profile already exists, we can directly take the user to their account.

Fix TP Login for accounts without CON profile

---

apps/redi-connect/src/pages/front/login/Login.tsx
apps/redi-connect/src/pages/front/signup/SignUp.tsx
apps/redi-talent-pool/src/pages/front/login/Login.tsx
apps/redi-talent-pool/src/pages/front/signup/SignUp.tsx

No issue.
When the cross-platform login didn't work, we changed the text on Login and SignUp pages. Now as the feature has been re-implemented, we want to revert the previous text.

fix(con/tp): revert the text for cross-platform login

---

apps/redi-connect/src/components/organisms/modules/MSessions.tsx

#624 
This PR disables selecting dates in the future, additionally it ensures the default date in the calendar is always set to today and that default values can be submitted.

[CON]fix: Disables future dates + allows default values to be submitted on mentoring sessions #624

---

apps/redi-connect/src/pages/front/signup/SignUp.tsx
apps/redi-connect/src/pages/front/signup/SignUpComplete.tsx
apps/redi-connect/src/pages/front/signup/SignUpLanding.scss
apps/redi-connect/src/pages/front/signup/SignUpLanding.tsx
apps/redi-connect/src/pages/front/signup/signup-page.type.ts

No issue.
There was a bug on the `Signup complete` page. The mentees and mentors did not see the information related to their type of user.
Signup complete page for mentees:
Signup complete page for mentors:

bugfix(con): fix userType check not working in SignUpComplete, conditionally render the Calendly link for mentees

---

apps/nestjs-api/src/assets/email/templates/footer.career.support.team-tp.mjml
apps/nestjs-api/src/assets/email/templates/reset-password.mjml
apps/nestjs-api/src/assets/email/templates/signup-complete-mentee-cyberspace.mjml
apps/nestjs-api/src/assets/email/templates/signup-complete-mentee.mjml
apps/nestjs-api/src/assets/email/templates/signup-complete-mentor.mjml
apps/nestjs-api/src/assets/email/tp-templates/jobseeker-profile-approved.mjml
apps/nestjs-api/src/assets/email/tp-templates/reset-password.mjml
apps/nestjs-api/src/assets/email/tp-templates/signup-complete-company--signup-type-existing-company.mjml
apps/nestjs-api/src/assets/email/tp-templates/signup-complete-company--signup-type-new-company.mjml
apps/nestjs-api/src/assets/email/tp-templates/signup-complete-jobseeker.mjml

No issue.
Paulina requested to replace her email footer to jobseekers with a Talent Success & Career Support Team footer and add one sentence to the sign-up emails.

chore(con/tp): update wording in the sign up emails

---

apps/redi-talent-pool/src/pages/app/browse/BrowseCompany.tsx
apps/redi-talent-pool/src/pages/app/browse/BrowseJobseeker.tsx
apps/redi-talent-pool/src/pages/app/me/MeCompany.tsx
apps/redi-talent-pool/src/pages/app/me/MeJobseeker.tsx

No issue.
No need to have these checkboxes on Jobseeker/Company Profile pages and Browse pages until the next Job Fair.

chore(tp): hide job fair checkboxes from user profiles and filters

---

apps/redi-connect/src/pages/app/me/Me.tsx
apps/redi-connect/src/pages/app/profile/Profile.tsx

No issue. 
When I commented out the Occupation section [here](apps/redi-connect/src/pages/app/me/Me.tsx), I verified only the mentee's `My Profile` page and didn't verify the mentor’s `My Profile` page. It turned out that the mentor's occupation was not displayed.

bugfix(con): display mentors occupation in their profile

---

libs/shared-atomic-design-components/src/lib/atoms/Button.scss

#791
I was not able to reproduce the issue exactly, as I could see the texts on my test devices (An iPhone and a ZTE Android device), however I was seeing the button text colors a bit differently so I decided to try tackling that.
**Before:**
**After:**
As I mentioned, this might require some back and forth with @astkhikatredi to make sure everything is fixed.

[#791] Fix text not shown on buttons for some browsers

---

libs/shared-atomic-design-components/src/lib/atoms/Button.tsx

No issue.
This PR fixes the UI of buttons on the location picker page.
Previously:
Now:

fix(con): fix buttons UI on location picker page

---

apps/redi-talent-pool/src/pages/app/me/TpCompanyProfileOnboardingSteps.scss
apps/redi-talent-pool/src/pages/app/me/TpCompanyProfileOnboardingSteps.tsx

#842
The company's stepper design has a UI bug, exhibiting issues such as a broken general layout, lack of borders, and misalignment of text and symbols. Please refer to the screenshots below for visual details.
Previously the profile pages (`MeCompany.tsx` & `MeJobseeker.tsx`) had the same parent `redi-talent-pool/src/pages/app/me/Me.tsx.` Each page had an `OnboardingSteps` component, but only `MeJobseeker.tsx` had a style file `MeJobseeker.scss` imported to it. Since those styles were global and `MeCompany.tsx`&`MeJobseeker.tsx` shared the parent, the styles were also applied to `MeCompany.tsx `, that uses the same classnames.
Currently, the profile pages don’t share a parent anymore, because the jobseeker profile now has id based urls.  `MeJobseeker.tsx` became …

bugfix(tp): recover styles for company profile stepper

---

apps/redi-connect/src/hooks/useNotAuthenticatedRedirector.ts
apps/redi-connect/src/pages/front/login/Login.tsx
apps/redi-talent-pool/src/hooks/useNotAuthenticatedRedirector.ts
apps/redi-talent-pool/src/pages/front/login/Login.tsx

#824
This PR ensures a user experiences when trying to access a CON/TP page requiring login but they aren't logged in:
1. Suppose user tries to access `/app/browse`, but isn't logged in
2. User redirected to `/front/login?goto=/app/browse` (the `/app/browse` is actually urlencoded so it actually becomes `%2Fapp%2Fbrowse`)
3. User logs in
4. Instead of being forwarded to the default path `/app/me`, user is sent to the "goto URL", i.e. `/app/browse`

feat(con/tp): direct to intended page after login

---

apps/redi-talent-pool/src/components/organisms/JobListingCard.scss

#841
To follow the [design](https://www.figma.com/file/COW83FbwUhEXsAQ88lIIW7/Job-Listings-Cards-Design-(Ticket-688)?node-id=119%3A2676&mode=dev) more closely, this PR adjusts the spacings between `JobTitle`, `CompanyName` and `Location`, aligns the `locationIcon` with the rest of the text, and reduces the space between the timestamp("x days ago") and the bottom limit of the card.
Previous implementation:
New Implementation:

fix(tp): adjustments to jobListingCard design

---

apps/nestjs-api/src/assets/email/templates/footer.janis.mjml
apps/nestjs-api/src/email/lib/email/email.js
apps/nestjs-api/src/email/lib/email/tp-email.js

#821 
This PR updates the footer in the emails that are sent to companies in TP:
* janis@redi... => partner@redi...
* Sender is now Janis Janowsky <partner@redi-school.org> instead of career@redi-school.org

feat: :sparkles: update footer and sender for tp emails

---

apps/redi-talent-pool/src/pages/app/me/Me.tsx
apps/redi-talent-pool/src/pages/front/login/LoginError.tsx
apps/redi-talent-pool/src/routes/routes__logged-out.tsx

#800 
This PR changes the behavior of redirecting PENDING, REJECTED and DEACTIVATED TP Company Representatives. Previously we were redirecting them to Signup Verification Success page, but with this PR, we are creating a new page for REJECTED and DEACTIVATED Reps and redirecting PENDING Reps to Signup Complete page. (Screenshots below)
There are a few open questions that can change the implementation when answered:
* @ericbolikowski what do you feel about the `login-error` URL? It sounds very generic but it's actually only being used for TP Comp Reps. Any better ideas?
**REJECTED/DEACTIVATED TP Comp Reps:**
**PENDING TP Comp Reps:**

feat: :sparkles: add navigating rejected & deactivated users to login error page

---

libs/common-types/src/lib/con-profile/enums/mentoring-topic.enum.ts
libs/data-access/src/lib/types/types.ts
libs/shared-config/src/lib/config.ts
schema.graphql

Closes #896 
Salesforce changes:
- Added a new value `Swedish` to the mentoring topics list on `partial`, `contp` & `production` orgs
Codebase changes:
- Added a new value `Swedish` to the mentoring topics list

feat(con): add Swedish to mentoring topics list

---

apps/nestjs-api/src/tp-company-profiles/tp-company-profiles-salesforce-event-handler.service.ts
apps/nestjs-api/src/tp-company-profiles/tp-company-profiles.service.ts
apps/redi-talent-pool/src/pages/app/me/MeCompany.tsx
apps/redi-talent-pool/src/pages/front/signup/SignUp.tsx

Closes #880.
In this PR,  we make sure that:
-  the company (company's job listings) automatically becomes visible to jobseekers after its profile has been approved
-  the `isProfileVisibleToJobseekers` checkbox is hidden from the company representative profile view until the company profile is approved
- cross-login information for the company representative user was removed because it is intended for jobseekers only
Drafting company profile:
Approved company profile:
Signup page for companies:

feat(tp): make company visible to jobseekers after its profile approval

---

apps/redi-talent-pool/src/components/organisms/JobListingCard.scss
apps/redi-talent-pool/src/components/organisms/JobListingCard.tsx
apps/redi-talent-pool/src/components/organisms/company-profile-editables/EditableJobPostings.tsx
libs/shared-atomic-design-components/src/lib/molecules/NewProfileCard.tsx

Closes #868 
In this PR, we:
- Fix the position of the 3-dots menu in the mobile view
- Remove the tooltip from the 3-dots menu
- Update the location wording on the mentor card (CON)
Job Listing card (mobile view):
Updated mentor card:

fix(tp): 3-dots menu

---

apps/redi-connect/src/components/organisms/ConfirmMentorship.tsx
apps/redi-connect/src/pages/app/applications/application-card/ApplicationCard.tsx
apps/redi-connect/src/pages/app/applications/application-card/MobileApplicationCard.tsx

Closes #997
When the mentor receives new mentee applications but has reached the mentee count they selected in their profile (or has reached our recommended mentee limit - 2 mentees), we disable the `Accept` button on the mentee's application and display the notification.
A mentor who has one ongoing mentorship & selected 1 in the mentee count:
A mentor who has two ongoing mentorships & selected 2 (our recommended maximum number of mentees) in the mentee count:

fix(con): mentors accept requests only within selected capacity

---

apps/nestjs-api/src/reminder-emails/reminder-emails.controller.ts
apps/nestjs-api/src/reminder-emails/reminder-emails.service.ts

feat: refactor reminder email service to use nodemailer instead of AWS SES

---

apps/nestjs-api/src/assets/email/templates/signup-complete-mentor.malmo.mjml
apps/nestjs-api/src/assets/email/templates/signup-complete-mentor.mjml
apps/redi-connect/src/pages/app/me/onboarding-steps-config.tsx

No issue.
This PR brings back the onboarding calls calendar link to the mentors' emails.
German mentors:
Malmö mentors:

chore(con): add onboarding calls calendar link to the mentors emails

---

apps/nestjs-api/src/assets/email/templates/pending-review-declined-email.malmo.mjml
apps/nestjs-api/src/assets/email/templates/pending-review-declined-email.mjml
apps/nestjs-api/src/con-profiles/con-profiles-salesforce-event-handler.service.ts

No issue.
Before introducing a `Submitted for review` profile status on CON, we sent the ‘Your user registration was declined’ email when the profile status was changed from `Drafting` to `Rejected`. The profile review process has changed, and now Mentorship Managers only review the profiles with a `Submitted for review` status. Therefore, we had to update the condition for sending the  ‘Your user registration was declined’ email to the following:
We send the ‘Your user registration was declined’ email when the profile status is changed from `Submitted for review` to `Rejected`.
Also, the wording of that email was updated.

fix(con): send the pending-review-declined-email on status change from submitted for review to rejected

---

apps/redi-connect/src/components/molecules/ReadMenteeCount.tsx
apps/redi-connect/src/components/organisms/EditableMenteeCount.tsx
apps/redi-connect/src/pages/app/profile/profile-viewer/ProfileViewer.tsx

No issue.
In this PR, we:
- Hide the `Apply for this mentor` button from the mentees who don't have an approved profile
- Hide information related to `optOutOfMenteesFromOtherRediLocation` from the mentor's profile page, as currently the majority of our students are taking classes online

bugfix(con): hide apply button from unapproved mentees; hide optOutOfMenteesFromOtherRediLocation info from mentor's profile page

---

apps/redi-connect/src/components/organisms/ConUserProfileCard.tsx
apps/redi-connect/src/pages/app/applications/application-card/ApplicationCard.scss
apps/redi-connect/src/pages/app/applications/application-card/ApplicationCard.tsx
apps/redi-connect/src/pages/app/applications/application-card/MobileApplicationCard.scss
apps/redi-connect/src/pages/app/applications/application-card/MobileApplicationCard.tsx
apps/redi-connect/src/pages/app/applications/application-card/useApplicationCard.ts
libs/shared-atomic-design-components/src/lib/atoms/CardTags.scss
libs/shared-atomic-design-components/src/lib/atoms/Chip.scss
libs/shared-atomic-design-components/src/lib/atoms/Chip.tsx
libs/shared-atomic-design-components/src/lib/atoms/FormSelect.styles.ts
libs/shared-atomic-design-components/src/lib/atoms/Icon.tsx
libs/shared-config/src/lib/config.ts

No issue.
In this PR, we:
- Changed the naming of the Cyberspace location and aligned it in multiple places
- Styled Chip and FormSelect components according to the new design system
- Styled the mentee application card according to the new design suggested by Becky
- Added chip/tag variants for different statuses of the mentee application card
ReDI location dropdown on the CON/TP sign-up page:
ReDI location dropdown on the 'Find a mentor' page:
Tags on the mentee/mentor profile page:
Tags in the multiselect dropdown:
Tags on the mentor profile card (desktop):
Tags on the mentor profile card (mobile):
ReDI location & tags on the mentor profile view:
New design of the application card (desktop):
New design of the application card (mobile):
Tags on the jobseeker profile card (desktop):
Tags …

feat(con/tp): update cyberspace location naming; style mentee application card; style and add variants to the Chip component
