ReDI-School/connect

- redi-connect-front/package.json
@khaledosman, this PR follows up on your comment in Slack. Does this fix correctly address the issue?
> feat(front): improve prod. deployment script

- redi-connect-front/src/components/Routes.tsx
- redi-connect-front/src/layouts/LoggedOutLayout.tsx
- redi-connect-front/src/pages/front/landing/Home.tsx
- redi-connect-front/src/pages/front/signup/SignUpLanding.tsx
- redi-connect-front/src/routes/routes__logged-out.tsx
- redi-connect-front/src/services/api/api.tsx
Add basic pages to the routing and define the new default route
> feat(front): adding landing pages to routing

- redi-connect-front/src/components/atoms/Button.scss
- redi-connect-front/src/components/atoms/Button.tsx
- redi-connect-front/src/components/organisms/LoggedOutNavbar.tsx
- redi-connect-front/src/components/organisms/PreFooter.tsx
- redi-connect-front/src/components/organisms/RediHero.tsx
- redi-connect-front/src/pages/front/login/Login.tsx
- redi-connect-front/src/pages/front/signup/SignUp.tsx
- redi-connect-front/src/styles/_variables.scss
the hover is still not the one form the design but maybe like this it will be also fine.
> fix(front): small fixes for the button

- redi-connect-front/src/components/molecules/Teaser.tsx
- redi-connect-front/src/components/organisms/LoggedOutNavbar.tsx
- redi-connect-front/src/components/organisms/RediHero.tsx
- redi-connect-front/src/pages/front/signup/SignUp.tsx
- redi-connect-front/src/pages/front/signup/SignUpComplete.tsx
- redi-connect-front/src/pages/front/signup/SignUpEmailVerification.tsx
- redi-connect-front/src/routes/routes__logged-out.tsx
I will try to figure out the change needed in backend on Monday. In case I need your support here will reach out.
> feat(front): adding email verification page

- redi-connect-backend/lib/email.js
This would be good to have today for the review. I hope its fine for you
> fix(front): fix sending emails on staging

- redi-connect-front/src/pages/front/signup/SignUp.tsx
- redi-connect-front/src/types/utility-types/Extends.ts
Small one, but it makes a difference
> fix(front): make enrolled course input required

- redi-connect-front/src/components/atoms/Button.scss
- redi-connect-front/src/components/atoms/FormInput.tsx
- redi-connect-front/src/components/organisms/PreFooter.scss
- redi-connect-front/src/components/organisms/PreFooter.tsx
- redi-connect-front/src/styles/_variables.scss
- redi-connect-front/src/styles/main.scss
small fixes that were requested in the testing
> feat(front): fixing smaller ui bugs for the home page 

- redi-connect-front/src/config/config.tsx
- redi-connect-front/src/pages/app/me/Mentoring.tsx
- redi-connect-front/src/types/Category.ts
I'm not really happy with the outcome so I would like you to take a look at it. 
All the groups are kind of interconnected and this triggers a re-render on every change.
> build(front): adding groups for the categories

- redi-connect-front/src/components/molecules/ReadMentoringTopics.tsx
- redi-connect-front/src/components/organisms/ConfirmMentorship.tsx
- redi-connect-front/src/components/organisms/ReportProblem.tsx
- redi-connect-front/src/components/organisms/SideMenu.tsx
- redi-connect-front/src/components/organisms/modules/MSessions.tsx
- redi-connect-front/src/components/templates/LoggedIn.tsx
- redi-connect-front/src/pages/app/mentorship/Mentorship.tsx
- redi-connect-front/src/pages/app/mentorship/MentorshipsList.tsx
- redi-connect-front/src/pages/app/profile/Profile.tsx
- redi-connect-front/src/types/RedMatch.ts
The redirects should be working now as expected. 
I'm not fully happy with the flow from the technical perspective but for now it should be fine. I know that there is plan to eventually kick out redux and this is the reason I decided against refactoring into the direction of firing a bunch of redux actions. I think under the hood, with the data flow we can do some improvements.
> fix(front): fix mentoring

- redi-connect-backend/lib/email/email.js
- redi-connect-front/src/components/molecules/Teaser.scss
- redi-connect-front/src/components/molecules/Teaser.tsx
- redi-connect-front/src/pages/front/login/Login.tsx
- redi-connect-front/src/pages/front/signup/SignUpEmailVerification.tsx
- redi-connect-front/src/routes/routes__logged-out.tsx
- `Teaser` image of Isabelle / Christa is now centered
- if you login to the wrong location you are not logged in anymore after refresh / navigating to the home page
- `sendVerificationEmail` url path edited to get the right teaser text (@ericbolikowski we should test this explicitly since the url generated for in development is not returning the right path)
> fix(front): bugs 'signup' fixed found after launch

- redi-connect-backend/lib/email/templates/validate-email-address-successful-mentor.berlin.mjml
- redi-connect-backend/lib/email/templates/validate-email-address-successful-mentor.munich.mjml
Doesn't need much explaining :)
> fix(backend): wording requested by Isabelle

- redi-connect-front/public/locales/en/translation.json
- redi-connect-front/src/pages/front/Faqs.scss
- redi-connect-front/src/pages/front/Faqs.tsx
- redi-connect-front/src/routes/routes__logged-out.tsx
As mentioned in Jira I am not quite sure if those are all the QAs but that's all I got from Anna. Might have to be edited tough.
> build(front): faqs page added

- redi-connect-infrastructure/_main.tf
fixes: https://github.com/talent-connect/connect/issues/239
Fixes some locations and some cosmosdb config on terraform
> fix: terraform locations

- redi-connect-admin/src/App.js
New filter for admins so they can filter by userActivates true/false
> feat(admin): RedProfile listing filter for userActivated yes/no

- .github/workflows/deploy-connect-backend.yml
- .github/workflows/deploy-connect-front.yml
- redi-connect-backend/server/datasources.json
- redi-connect-infrastructure/_main.tf
- redi-connect-infrastructure/_variables.tf
- redi-connect-infrastructure/staging.auto.tfvars
closes: https://github.com/talent-connect/connect/issues/232
Long story short, we create two different environments one production and one staging using Terraform's workspaces. 
After this PR is merged the front webapp will also be having a staging and a production environment. 
- on staging we will be hitting the https://app-staging-redi.azurewebsites.net/api. 
- on production we will be hitting the https://app-prod-redi.azurewebsites.net/api
After this is merged on `develop` you will be able to visit the staging env [here](https://cdn-endpoint-front-staging-redi.azureedge.net) and the production env [here](https://cdn-endpoint-front-prod-redi.azureedge.net)
> feat: creates two environments one staging and one production 

- .github/workflows/deploy-connect-backend.yml
> chore: adds the secrets

- .github/workflows/deploy-connect-backend.yml
- .github/workflows/deploy-connect-front.yml
- .github/workflows/terraform.yml
- redi-connect-infrastructure/_main.tf
- redi-connect-infrastructure/_output.tf
Adding staging and production environments for terraform github actions. The flow is the same as the other two. When something is merged on `develop` we basically deploy automatically on staging. Then uppon manual approval the changes are deployed on the production environment as well
@ericbolikowski see if you wanna have a quick look on this. I will leave it here till tomorrow :) if you dont have the time to give me your thumbs up I will merge it then
> chore: apply for different workspaces

- README.md
- redi-connect-backend/yarn.lock
- redi-connect-front/src/components/atoms/FormTextArea.scss
- redi-connect-front/src/components/atoms/FormTextArea.tsx
- redi-connect-front/src/components/organisms/ApplyForMentor.tsx
- redi-connect-front/src/components/organisms/ConfirmMentorship.tsx
- redi-connect-front/src/components/organisms/EditableAbout.tsx
- redi-connect-front/src/components/organisms/ReportProblem.tsx
described under
https://github.com/talent-connect/connect/issues/151
> Character Count underneath a textarea

- redi-connect-front/src/pages/app/find-a-mentor/FindAMentor.tsx
- redi-connect-front/src/services/api/api.tsx
Search field to look up mentors.
> feat(front): mentor search-by-name

- apps/redi-connect/src/components/organisms/ProfileCard.scss
- apps/redi-connect/src/components/organisms/ProfileCard.tsx
- apps/redi-connect/src/pages/app/find-a-mentor/FindAMentor.scss
- apps/redi-connect/src/pages/app/find-a-mentor/FindAMentor.tsx
- apps/redi-connect/src/services/api/api.tsx
> feat: filter by location

- apps/redi-talent-pool/src/components/molecules/CvPdfPreview.tsx
- apps/redi-talent-pool/src/pages/app/cv-wizard/CVWizardContainer.tsx
- package.json
- yarn.lock
This PR is a work in progress of a POC, to calculate the following values, in the Left Content Column of the CV PDF Preview:
* Current Height
* Max Height
* Remaining Height
Using these values, a progress bar can be built in any part of the page, informing the user how much more space they can use or even blocking them to add more information than the space they have.
* Checkout to this branch locally
* Run the CV Wizard
* Add information on the left side (About, Languages, Rewards etc.)
* Check the browser console (debug) to follow the values mentioned above
> Add left content col height calculation

- apps/redi-talent-pool/src/pages/app/cv/CvList.tsx
- apps/redi-talent-pool/src/react-query/use-tpjobseekercv-mutation.ts
- apps/redi-talent-pool/src/react-query/use-tpjobseekercv-query.ts
- apps/redi-talent-pool/src/routes/routes__logged-in.tsx
- apps/redi-talent-pool/src/services/api/api.tsx
- apps/redi-talent-pool/src/utils/build-frontend-url.ts
- libs/shared-atomic-design-components/src/lib/atoms/Heading.tsx
https://github.com/talent-connect/connect/issues/368
> Add CV List Page

- apps/redi-connect/src/pages/app/profile/Profile.scss
- apps/redi-connect/src/pages/app/profile/Profile.tsx
> Style location tag in mentor's profile

- apps/api/lib/email/tp-templates/company-validate-email-address-successful.mjml
> Update Company Verification Success email

- apps/redi-talent-pool/src/components/organisms/company-profile-editables/EditableDetails.tsx
- apps/redi-talent-pool/src/components/organisms/company-profile-editables/EditableJobPostings.tsx
- apps/redi-talent-pool/src/pages/app/me/MeCompany.tsx
> [Issue #426] Tp Company Profile Validations & Improvements

- apps/api/daily-cronjob-reminder-email/pending-mentorship-application-reminder.js
- apps/api/lib/email/daily-cronjob-reminder-email.js
> fix(api): minor bug in automated reminder emails

- apps/admin-panel/src/App.jsx
> [Issue #411] Add filters for company profiles in the Admin Panel

- apps/api/common/models/tp-company-profile.js
- apps/api/lib/email/tp-email.js
- apps/api/lib/email/tp-templates/company-profile-submitted-for-review.mjml
Fixes #443 
@ericbolikowski I put Birgit's email directly in the function, but I'm all ears if there's a smarter way to handle this.
> [Issue 443] Send TpCompanyProfile submitted for review email

- apps/redi-connect/src/services/api/api.tsx
- apps/redi-talent-pool/src/services/api/api.tsx
None.
This is a long-running code hygiene issue: our usernames are case-sensitive. This PR fixes that, by consistently lower-casing the username on both sign-up and log-in.
> fix(con/tp): make email username non-case sensitive

- apps/admin-panel/src/App.jsx
- apps/redi-talent-pool/src/pages/front/signup/SignUp.tsx
- libs/shared-config/src/lib/config.ts
- libs/shared-types/src/lib/TpCompanyProfile.ts
- libs/talent-pool/config/src/lib/talent-pool-config.ts
> [Issue #454] Add how did you hear about redi school questions

- libs/talent-pool/config/src/lib/talent-pool-config.ts
#454 
Updating the incorrect options in the dropdown.
> [#454] Update how did you hear about us options

- apps/redi-talent-pool/src/components/organisms/Avatar.tsx
- apps/redi-talent-pool/src/components/organisms/company-profile-editables/EditableNamePhotoLocation.tsx
> [Issue 470] Change Add Your Picture message for companies

- apps/admin-panel/src/App.jsx
- apps/admin-panel/src/utils/csvExport.js
> [Issue 477] Add more fields to Red Matches CSV

- README.md
None
Fixed the Talent Pool link which was broken, and added a link to the ReDI homepage.
> small fixes to the README file: url for TP and link to ReDI website

- libs/talent-pool/config/src/lib/talent-pool-config.ts
> Add Dual Study Bachelor and Master for TP Desired Positions

- libs/talent-pool/config/src/lib/talent-pool-config.ts
This PR simply adds the following:
**Positions**
* IoT developer
* Hardware developer
* Embedded systems engineer
**Skills**
* Embedded systems
* IoT
* Hardware
* CAD
> Add More Positions and Skills for TP

- apps/redi-talent-pool/src/components/molecules/TpTeaser.tsx
> changed link for signup

- apps/admin-panel/src/App.jsx
Request from Product Owner to display the optOutOfMenteesFromOtherRediLocation property in admin
> feat(admin): display RedProfile.optOutOfMenteesFromOtherRediLocation

- apps/admin-panel/src/App.jsx
> bug-issue #531

- apps/redi-connect/src/pages/front/reset-password/RequestResetPasswordEmail.tsx
- apps/redi-talent-pool/src/components/molecules/TpTeaser.tsx
- apps/redi-talent-pool/src/pages/front/reset-password/RequestResetPasswordEmail.tsx
- apps/redi-talent-pool/src/pages/front/signup/SignUp.tsx
- apps/redi-talent-pool/src/pages/front/signup/SignUpLanding.tsx
> centered illustration signup page #376

- apps/api/lib/email/templates/validate-email-address-successful-mentee.mjml
#515 
The Schedule button looks a bit low resolution but it might be due to the preview tool I use.
**Desktop:**
**Mobile:**
> Update Validate Email Address Successful Mentee email

- apps/api/lib/email/daily-cronjob-reminder-email-templates/mentorship-is-weeks-old-so-request-feedback_mentee.mjml
- apps/api/lib/email/daily-cronjob-reminder-email-templates/mentorship-is-weeks-old-so-request-feedback_mentor.mjml
- apps/api/lib/email/daily-cronjob-reminder-email-templates/no-mentoring-session-logged-yet-second-reminder_mentee.mjml
- apps/api/lib/email/daily-cronjob-reminder-email-templates/no-mentoring-session-logged-yet-second-reminder_mentor.mjml
- apps/api/lib/email/daily-cronjob-reminder-email-templates/no-mentoring-session-logged-yet_mentee.mjml
- apps/api/lib/email/daily-cronjob-reminder-email-templates/no-mentoring-session-logged-yet_mentor.mjml
- apps/api/lib/email/daily-cronjob-reminder-email-templates/pending-mentorship-application-reminder_mentor.mjml
- apps/api/lib/email/daily-cronjob-reminder-email.js
- apps/api/lib/email/templates/complete-mentorship-for-mentee.mjml
- apps/api/lib/email/templates/complete-mentorship-for-mentor.mjml
> chore(con): update 4 emails

- apps/redi-talent-pool/src/pages/front/signup/SignUp.tsx
No Issue
This PR adds an additional field in the sign-up process of TpJobseeker, which is Current ReDI Location field. Using this field, the courses that the jobseeker can select is filtered. Each location-course list has their own Alumni selection now, which should fix the problem of determining alumnis always as Berlin.
> Filter courses by location when TpJobseeker signs up

- apps/redi-connect/src/pages/front/reset-password/RequestResetPasswordEmail.tsx
- apps/redi-connect/src/pages/front/signup/SignUp.tsx
- apps/redi-talent-pool/src/pages/front/reset-password/RequestResetPasswordEmail.tsx
- apps/redi-talent-pool/src/pages/front/signup/SignUp.tsx
- libs/shared-config/src/lib/config.ts
> [Chore]: Update courses list

- apps/redi-connect/src/components/organisms/ApplyForMentor.tsx
- apps/redi-connect/src/components/organisms/CompleteMentorship.tsx
- apps/redi-connect/src/components/organisms/ConfirmMentorship.tsx
- apps/redi-connect/src/components/organisms/DeclineMentorshipButton.tsx
- apps/redi-connect/src/components/organisms/EditableAbout.tsx
- apps/redi-connect/src/components/organisms/ReportProblem.tsx
- apps/redi-talent-pool/src/components/organisms/company-profile-editables/EditableAbout.tsx
- apps/redi-talent-pool/src/components/organisms/company-profile-editables/EditableJobPostings.tsx
- apps/redi-talent-pool/src/components/organisms/company-profile-editables/EditableNamePhotoLocation.tsx
- apps/redi-talent-pool/src/components/organisms/jobseeker-profile-editables/EditableEducation.tsx
- apps/redi-talent-pool/src/components/organisms/jobseeker-profile-editables/EditableImportantDetails.tsx
- apps/redi-talent-pool/src/components/organisms/jobseeker-profile-editables/EditableProfessionalExperience.tsx
- apps/redi-talent-pool/src/components/organisms/jobseeker-profile-editables/EditableSummary.tsx
- apps/redi-talent-pool/src/react-query/use-tpjoblisting-update-mutation.ts
- libs/shared-atomic-design-components/src/lib/atoms/FormTextArea.tsx
- libs/shared-atomic-design-components/src/lib/styles/_forms.scss
#594
According to the discussion with Patricia and the design team, I also updated the wording in the ApplyForMentor component in this PR.
> chore: add props to FormTextArea component

- apps/redi-connect/src/components/organisms/EditableLanguages.tsx
- apps/redi-talent-pool/src/components/organisms/company-profile-editables/EditableJobPostings.tsx
- apps/redi-talent-pool/src/components/organisms/jobseeker-profile-editables/EditableImportantDetails.tsx
- apps/redi-talent-pool/src/components/organisms/jobseeker-profile-editables/EditableOverview.tsx
- apps/redi-talent-pool/src/components/organisms/jobseeker-profile-editables/EditableSummary.tsx
- libs/shared-atomic-design-components/src/lib/atoms/FormSelect.tsx
> fix(tp): allow multi-select with drop-down open

- apps/redi-connect/src/components/organisms/EditableContactDetails.tsx
- apps/redi-connect/src/pages/front/signup/SignUp.tsx
- apps/redi-talent-pool/src/components/organisms/company-profile-editables/EditableContact.tsx
- apps/redi-talent-pool/src/components/organisms/jobseeker-profile-editables/EditableNamePhotoLocation.tsx
- apps/redi-talent-pool/src/pages/front/signup/SignUp.tsx
- libs/shared-utils/src/index.ts
- libs/shared-utils/src/lib/to-pascal-case.ts
> fix(con/tp): apply pascal-casing and trimming on first/last name fields 

- apps/api/lib/email/tp-templates/company-profile-approved.mjml
> update company profile approved message

- apps/admin-panel/src/App.jsx
- apps/redi-talent-pool/src/pages/app/me/MeCompany.tsx
- libs/shared-types/src/lib/TpCompanyProfile.ts
> feat(tp): company-profile-checkbox-attending-job-fair-2023

- apps/redi-talent-pool/src/components/organisms/Footer.tsx
> Fixes spacing on footer elements & title

- apps/admin-panel/src/App.jsx
> feat(admin): add course column for Tpjobseekerprofiles

- apps/api/lib/email/tp-email.js
#443 
This PR adds Janis's email address to the recipients of the email when a company request approval.
> [#443] Add Janis to company approval request emails

- apps/redi-connect/src/components/organisms/EditableRediClass.tsx
- apps/redi-connect/src/pages/front/signup/SignUp.tsx
- libs/shared-config/src/lib/config.ts
> fix(con/tp): fix courses list on CON and TP

- apps/nestjs-api/src/assets/email/templates/schedule-onboarding-call-for-tp-jobseeker-signed-up-as-mentee-cyberspace.mjml
- apps/nestjs-api/src/assets/email/templates/signup-complete-mentee-cyberspace.mjml
> fix(con): update Josefas link for mentees activation calls

- apps/nestjs-api/src/assets/email/templates/signup-complete-mentee.mjml
- apps/nestjs-api/src/salesforce-api/sf-api-tp-company-profiles.service.ts
- apps/nestjs-api/src/tp-company-profiles/use-cases/tp-company-profile-sign-up/tp-company-profile-sign-up.mutation-dtos.ts
- apps/nestjs-api/src/tp-company-profiles/use-cases/tp-company-profile-sign-up/tp-company-profile-sign-up.use-case.ts
- apps/redi-talent-pool/src/pages/front/signup/SignUp.tsx
#725 
The checkbox appears only when a new company is being created. If there is a representative who signs up for an existing company, this checkbox won't appear for them.
> feat(tp): add isMicrosoft partner checkbox to the new company sign up 

- apps/nestjs-api/src/assets/email/templates/footer.berlin.eric.mjml
- apps/nestjs-api/src/assets/email/templates/footer.berlin.paulina.mjml
- apps/nestjs-api/src/assets/email/templates/footer.berlin.zoe.mjml
- apps/nestjs-api/src/assets/email/templates/footer.career.support.team.mjml
> fix(con): update ReDI address in the email footers

- apps/redi-talent-pool/src/pages/front/signup/SignUp.tsx
Bug report: The company representative gets a ‘white screen’ when logged in. There is an error during sign-up step:
> fix(tp): provide default value for isMicrosoftPartner 

- apps/redi-connect/src/pages/front/login/Login.tsx
:x: Location check doesn’t work for cross-login. The user can log in to CON in a different location than they selected when signing up on TP.
This was happening because in case the user doesn't have a CON profile but TP Profile, we were not checking if the rediLoaction of the TP Profile matches with the env location. On top of this, we were creating the new CON profile with the env location, (which could create issues of same user having two locations for CON/TP profiles)
This PR compares the rediLocation from the TP profile with the env location and shows the same error message if there's a mismatch
> Detect location mismatch when cross login to connect

- apps/nestjs-api/src/assets/email/templates/signup-complete-mentor.mjml
- apps/redi-connect/src/pages/front/signup/SignUpComplete.tsx
> chore(con): change the mentor onboarding link

- apps/nestjs-api/src/tp-company-profiles/use-cases/tp-company-profile-sign-up/tp-company-profile-sign-up.use-case.ts
> fix(tp/signupusecase): upsert AccountContactRelationship to allow existing ones

- apps/redi-connect/src/pages/app/applications/application-card/MobileApplicationCard.tsx
- apps/redi-talent-pool/src/components/molecules/CardContextMenu.tsx
- apps/redi-talent-pool/src/components/molecules/Editable.tsx
- apps/redi-talent-pool/src/components/organisms/Avatar.tsx
- apps/redi-talent-pool/src/components/organisms/ExpiredJobListings.tsx
- apps/redi-talent-pool/src/components/organisms/company-profile-editables/EditableJobPostings.tsx
- apps/redi-talent-pool/src/components/organisms/jobseeker-profile-editables/EditableEducation.tsx
- apps/redi-talent-pool/src/components/organisms/jobseeker-profile-editables/EditableImportantDetails.tsx
- apps/redi-talent-pool/src/components/organisms/jobseeker-profile-editables/EditableProfessionalExperience.tsx
- apps/redi-talent-pool/src/pages/app/browse/BrowseCompany.tsx
- apps/redi-talent-pool/src/pages/app/browse/BrowseJobseeker.tsx
- apps/redi-talent-pool/src/pages/app/job-listing/JobListing.tsx
- apps/redi-talent-pool/src/pages/app/jobseeker-profile/JobseekerProfileForJobseekerEyes.tsx
- apps/redi-talent-pool/src/pages/app/me/MeCompany.tsx
- apps/redi-talent-pool/src/pages/app/me/TpCompanyProfileOnboardingSteps.tsx
No issue. 
In this PR, we:
- Add validation rule for the `salaryRange` field in the job listing modal, fixing [this issue](https://redi-school.slack.com/archives/C0556JQE5K4/p1710347805039129?thread_ts=1710318477.718329&cid=C0556JQE5K4) reported by a company representative:
- Hide the stepper for jobseekers with the `Approved` profile status:
- Make the stepper _visible on mobile_ in the company representative profile view:
- Hide the `Send Profile For Review` button if the profile status of the company representative and jobseeker is `SubmittedForReview`:
- Fixed console react warnings related to invalid `textSize` prop and missing `key` prop (visible in development): 
- Fixing the `textSize` prop also fixed the size of the _section titles in the mobile view_ for multiple components. …
> fix(tp): fixed miscellaneous bugs & console warnings on TP

- apps/redi-talent-pool/src/components/organisms/JobListingCard.scss
- apps/redi-talent-pool/src/components/templates/LoggedIn.scss
- apps/redi-talent-pool/src/components/templates/LoggedIn.tsx
- libs/shared-atomic-design-components/src/lib/atoms/CardLocation.tsx
- libs/shared-atomic-design-components/src/lib/styles/_main.scss
Ticket [#881](https://github.com/talent-connect/connect/issues/881)
- The peragraph which diplays the job title is not hidding the overflowed content, giving overfow:hidden to it or/and it's parent did not solve the issue, this compoent is nested in losts of components and i had to track all it's parents to the find the parents compoents that are responsible for this issue, i found them and gave them overflow:hidden and this has solved the problem. 
- After the fix 
Responsive
> Feature/bugfix/talent pool/job listing card display bug #881

- apps/nestjs-api/src/assets/email/templates/welcome-to-redi-mentee.mjml
- apps/redi-connect/src/assets/locales/en/translation.json
- apps/redi-connect/src/pages/app/me/onboarding-steps-config.tsx
> chore(con): replace outdated Calendly link for the consultancy calls

- apps/nestjs-api/src/assets/email/templates/welcome-to-redi-mentee.malmo.mjml
- apps/redi-connect/src/pages/app/me/onboarding-steps-config.tsx
> chore(con): update calendar link for Malmo mentors

- apps/nestjs-api/src/assets/email/templates/welcome-to-redi-mentee.malmo.mjml
- apps/redi-connect/src/pages/app/me/onboarding-steps-config.tsx
> Update the link for Malmo mentors (#1007)

- apps/nestjs-api/src/assets/email/templates/footer.career.support.team.mjml
- apps/redi-connect/src/assets/locales/en/translation.json
> chore(con): update the email footer for the Career Support Team

- apps/nestjs-api/src/assets/email/templates/mentoring-session-logged-email.malmo.mjml
- apps/nestjs-api/src/assets/email/templates/mentoring-session-logged-email.mjml
- apps/nestjs-api/src/assets/email/templates/mentorship-request-email.malmo.mjml
- apps/nestjs-api/src/assets/email/templates/mentorship-request-email.mjml
- apps/nestjs-api/src/assets/email/templates/signup-complete-mentee.malmo.mjml
- apps/nestjs-api/src/assets/email/templates/signup-complete-mentee.mjml
- apps/nestjs-api/src/assets/email/templates/welcome-to-redi-mentee.malmo.mjml
- apps/nestjs-api/src/assets/email/templates/welcome-to-redi-mentee.mjml
- apps/nestjs-api/src/assets/email/templates/welcome-to-redi-mentor.malmo.mjml
- apps/nestjs-api/src/assets/email/templates/welcome-to-redi-mentor.mjml
- apps/redi-connect/src/assets/locales/en/translation.json
> fix(con): replace mj-image buttons with mj-buttons in the rest of the emails

- apps/nestjs-api/src/assets/email/templates/welcome-to-redi-mentee.mjml
- apps/redi-connect/src/assets/locales/en/translation.json
- apps/redi-connect/src/pages/app/profile/profile-editor/onboarding-steps-config.tsx
> chore(con): update calendar link for mentees
